spring.application.name=IBM Innovate

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

#daniellas email + login for OTPs
spring.mail.username=Odiella1226@gmail.com
spring.mail.password=Taehyung_611
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mysql://localhost:3306/co2302db
spring.datasource.username=root
#change to your password to use db
spring.datasource.password=Chadan_1220
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
#should be on update to keep data
#using create-drop in practice
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Add these alongside your create-drop setting
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.security.oauth2.client.registration.google.client-id= 791845252251-9hi5g8f4d2vjctpovs402gvretkntf9n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Serve static resources from both the uploads folder and the default static locations
spring.web.resources.static-locations=file:uploads/, classpath:/static/images/, classpath:/static/js, classpath:/static/animation, classpath:/static/css





