spring.application.name=hw2

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:mysql://localhost:3306/co2302db
spring.datasource.username=co2302
spring.datasource.password=Gr0up27isthebest123.
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug